# File: .pre-commit-config.yaml
repos:
-   repo: https://github.com/psf/black
    rev: 24.1.1  # Use the latest stable version
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=88]  # Optional: customize line length

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest stable version
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-black]
        args: [--max-line-length=88]