# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace  # Removes trailing whitespace
    -   id: end-of-file-fixer  # Ensures files end with a newline
    -   id: check-yaml  # Validates yaml syntax
    -   id: check-json  # Validates json syntax
    -   id: check-toml  # Validates toml syntax
    -   id: check-added-large-files  # Prevents giant files from being committed
        args: ['--maxkb=500']
    -   id: check-merge-conflict  # Checks for files containing merge conflict strings
    -   id: check-case-conflict  # Checks for files with names that would conflict on case-insensitive filesystems
    -   id: mixed-line-ending  # Replaces or checks mixed line endings
        args: ['--fix=lf']
    -   id: detect-private-key  # Checks for presence of private keys
    -   id: debug-statements  # Check for debugger imports and breakpoints in Python

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black  # Python code formatter
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort  # Sorts Python imports
        args: ['--profile', 'black']  # Makes isort compatible with black

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8  # Python linter
        additional_dependencies: [
            'flake8-bugbear',  # Finds likely bugs
            'flake8-comprehensions',  # Helps write better list/set/dict comprehensions
            'flake8-docstrings',  # Checks docstring conventions
            'flake8-quotes',  # Enforces consistent quote usage
        ]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier  # Formats various file types (JavaScript, TypeScript, CSS, JSON, etc.)
        types_or: [javascript, jsx, ts, tsx, css, scss, json, yaml, markdown]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
    -   id: eslint  # JavaScript/TypeScript linter
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        -   eslint
        -   eslint-config-prettier
        -   '@typescript-eslint/eslint-plugin'
        -   '@typescript-eslint/parser'

-   repo: local
    hooks:
    -   id: test-suite
        name: Run Test Suite
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]  # Only run on push, not on every commit